### ISSUE TITLE
Can't search

### ISSUE THREAD

**Issue by gwendolynemaxinegwenstacy** [WeeabooGod/Greenluma-Reborn-Manager#2]
Well, i tried to search with appid and name but nothing happens after: getting app list... - always get no result. 

Installed: Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019

**Comment by WeeabooGod** [comment]
You search only with name. For example "Monster Hunter". AppID doesn't count I believe. If you can, post a picture of your problem so I can have a better understanding of what your doing.

https://i.imgur.com/ajXgxJO.png

**Comment by gwendolynemaxinegwenstacy** [comment]
> Monster Hunter

Hello, sorry for the late reply.

It just doesn't load anything.

https://imgur.com/a/WxEduB2

**Comment by WeeabooGod** [comment]
Alright, some testing on my end, do you have.... in the root folder look into "Resources". Do you have a file called "cacert.pem". 

If you do not then that explains why it doesn't work. You need that for authorization, program SHOULD be making it for you (Though the download should also included). Please confirm the existence (or lack thereof). If it doesn't exist re download (I also did a small update but it doesn't fix anything functionally). If it does let me know.
